import "dotenv/config";

const constants = {
    PORT: process.env.PORT,
    NODE_ENV: process.env.NODE_ENV,
    MONGO_URI: process.env.MONGO_URI,
    ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRY: process.env.ACCESS_TOKEN_EXPIRY,
    REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY,
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_SECRET: process.env.CLOUDINARY_SECRET,
    CLOUDINARY_IMAGE_MODERATION: process.env.CLOUDINARY_IMAGE_MODERATION,
    ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS?.split(","),
    FRONTEND_URL: process.env.FRONTEND_URL,
    OPENAI_API_MODEL: process.env.OPENAI_API_MODEL,
    GMAIL_API_CLIENT_ID: process.env.GMAIL_API_CLIENT_ID,
    GMAIL_API_CLIENT_SECRET: process.env.GMAIL_API_CLIENT_SECRET,
    GMAIL_API_REDIRECT_URI: process.env.GMAIL_API_REDIRECT_URI,
    GMAIL_API_REFRESH_TOKEN: process.env.GMAIL_API_REFRESH_TOKEN,
    AUTHORIZE_MAIL: process.env.AUTHORIZE_MAIL,
    RECEIVER_MAIL: process.env.RECEIVER_MAIL,
};

export default constants;
